#!/usr/bin/env bash
# shellcheck disable=SC2046
shellcheck $(
  find "src" -type f &&
  find "test/fixtures" -type f -name "*.bash" &&
  find "test" -type f -maxdepth 1 -name "*.bash" -or -name "*.bats"
)
