#!/usr/bin/env bash
#
# This script downloads a specific bee version into your current working directory
# Run
# bash -c "BEE_VERSION=<YOUR_VERSION>;$(curl -fsSL https://raw.githubusercontent.com/sschmid/bee/master/get)"

set -e

export GIT_LFS_SKIP_SMUDGE=1
git clone --depth 1 --branch "${BEE_VERSION}" git@github.com:sschmid/bee.git
