#!/usr/bin/env bash
#
# This script installs to /usr/local only
# To install, run
# bash -c "$(curl -fsSL https://raw.githubusercontent.com/sschmid/bee/main/install)"

set -e

LOCAL_REPO=/usr/local/opt/bee
REPO=https://github.com/sschmid/bee

if [[ -d "${LOCAL_REPO}" ]]; then
  echo "It seems like bee is already installed at ${LOCAL_REPO}"
  echo "Run 'bee update' to update bee to the latest version"
else
  git clone "${REPO}" "${LOCAL_REPO}"
  echo "Linking ${LOCAL_REPO}/src/bee to /usr/local/bin/bee"
  mkdir -p /usr/local/bin
  ln -s "${LOCAL_REPO}/src/bee" /usr/local/bin/bee
  cat << 'EOF'
Please enable bee bash completion to enjoy the best bee experience:

  echo "complete -C bee bee" >> ~/.bashrc

For zsh also add this:

  echo "autoload bashcompinit" >> ~/.zshrc
  echo "bashcompinit" >> ~/.zshrc

🐝 bee has been installed successfully
EOF
fi
