#!/usr/bin/env bash
#
# This script installs to /usr/local only
# To install, run
# bash -c "$(curl -fsSL https://raw.githubusercontent.com/sschmid/bee/master/install)"

set -e

LOCAL_REPO=/usr/local/opt/bee
SYM_LINK=/usr/local/bin/bee
REPO=https://github.com/sschmid/bee

if [[ -d "${LOCAL_REPO}" ]]; then
  echo "It seems like bee is already installed at ${LOCAL_REPO}"
  echo "Run 'bee update' to update bee to the latest version"
else
  git clone "${REPO}" "${LOCAL_REPO}"
  echo "symlink to ${SYM_LINK}"
  ln -s "${LOCAL_REPO}/libexec/bee" "${SYM_LINK}"
  echo "🐝 bee has been installed successfully"
fi
