#!/usr/bin/env bash

assert_file() {
  if [[ ! -f "${!1}" ]]; then
    echo "❌ ASSERT $1: file not found: ${!1}" >&2
    exit 1
  fi
}

require() {
  command -v "$1" &>/dev/null || {
    log_error "$1 not found! $1 is required."
    exit 1
  }
}

source_config() {
  local config="${HOME}/.beerc"
  if [[ ! -f "${config}" ]]; then
    echo "#!/usr/bin/env bash" > "${config}"
    echo 'BEE_PLUGINS="${BEE_HOME}/plugins"' >> "${config}"
    echo 'BEE_USER_PLUGINS="${HOME}/.bee/plugins"' >> "${config}"
  fi
  source "${config}"
}

source_plugins() {
  for p in "$@"; do
    local f="${BEE_PLUGINS}/${p}/${p}.sh"
    local uf="${BEE_USER_PLUGINS}/${p}/${p}.sh"
    if [[ -f "${f}" ]]; then
      source "${f}"
    elif [[ -f "${uf}" ]]; then
      source "${uf}"
    else
      log_error "Could not find plugin ${p}"
      exit 1
    fi
  done
}
