#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

if (( ! $# || $# == 1 && COMP_PARTIAL )); then
  echo --clear
elif (( $# == 1 || $# == 2 && COMP_PARTIAL )); then
  [[ ! -d "${BEE_CACHE_PATH}" ]] || ls "${BEE_CACHE_PATH}"
fi
