#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

########################################
# Delete cache directories
# Arguments:
#   options, subdirectory
########################################

if (( $# )); then
  case "$1" in
    --clear) rm -rf "${BEE_CACHE_PATH}${2:+/$2}" ;;
    *) "${BEE_HOME}/src/help"; exit 1 ;;
  esac
else
  os_open "${BEE_CACHE_PATH}"
fi
