#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

########################################
# Hash files in a directory
# Arguments:
#   directory
# Outputs:
#   Single hash for all files in directory
########################################

if (( ! $# )); then
  bee::help
  exit 1
fi

declare -a exclude=(^./.git .DS_Store$)
declare -a hashes=()
declare -i ignore=0

# shellcheck disable=SC2207
[[ -v BEE_HUB_HASH_EXCLUDE ]] && exclude+=($(bee::split_args "${BEE_HUB_HASH_EXCLUDE:-}"))

echo "$1" >&2

pushd "$1" >/dev/null || exit 1
  while read -r file; do
    ignore=0
    for pattern in "${exclude[@]}"; do
      if [[ "${file}" =~ ${pattern} ]]; then
        ignore=1
        break
      fi
    done
    if (( ! ignore )); then
      file_hash="$(os_sha256sum "${file}")"
      echo "${file_hash}" >&2
      hashes+=("${file_hash// */}")
    fi
  done < <(find . -type f | LC_ALL=C sort)
popd >/dev/null || exit 1

all="$(echo "${hashes[*]}" | LC_ALL=C sort | os_sha256sum)"
echo "${all}" >&2
echo "${all// */}"
