#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

if (( ! $# || $# == 1 && COMP_PARTIAL )); then
  echo --latest
elif (( $# == 1 || $# == 2 && COMP_PARTIAL )); then
  case "${1:-}" in
    --latest) echo "--cached" ;;
  esac
fi
